version: "3.8"

services:
  web:
    build: .
    container_name: my_dreams
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
    command: flask run --host=0.0.0.0
